load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

kt_jvm_library(
    name = "default",
    srcs = [
        "ReleaseParser.kt",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
