load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")

kt_jvm_library(
    name = "default",
    srcs = [
        "DateFormat.kt",
        "DateTime.kt",
    ],
    visibility = ["//visibility:public"],
)
