load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "default",
    srcs = [
        "Csv.kt",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_github_doyaaaaaken_kotlin_csv_jvm",
    ],
)
